### ISSUE TITLE
Account update fails with "500 Internal Server Error".

### ISSUE THREAD

**Issue by pla1** [alexloehner/linuxcounter.new#1]
Changing account information at http://test.linuxcounter.net/info/edit throws a 500 error after hitting the Update button. I tried it several times while changing different fields. It doesn't appear to matter what you are changing it throws the 500 error every time. 

**Oops! An Error Occurred**

**The server returned a "500 Internal Server Error".**

**Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.**

**Comment by alexloehner** [comment]
Can you please try this again? There was a small caching problem at that time. It should work now.

**Comment by pla1** [comment]
Still happening. ![Screenshot] (http://i.imgur.com/dcfIBeP.png)

**Comment by alexloehner** [comment]
Can you please send me a screenshot of the completely filled form that you are submitting?
Please send the screenshot to: info@linuxcounter.net.
Thanks

**Comment by alexloehner** [comment]
okay, let me guess... you have left one of the two date fields completly empty, right? This way I was able to reproduce an error. I'll fix that now.

**Comment by alexloehner** [comment]
Okay, this should be fixed now.

**Comment by pla1** [comment]
Looks like everything works except for the city field. There doesn't appear to be any US cities in the type-ahead results. If I ignore the type-ahead results and key my city is not saved.

**Comment by alexloehner** [comment]
@pla1 can you please create a new ticket for this problem, please? Would be cool ;)
