### ISSUE TITLE
lico-update won't update data of old systems

### ISSUE THREAD

**Issue by HaleyACS** [alexloehner/linuxcounter.new#38]
Trying to update the data of my systems as I recently upgraded 2 of them - and I am unable to update these.
The lico update correctly finds the data, and correctly sends it out (Checked the curl-call), however looking at the interface (WebUI) after, the changes are not visible. Still old data inside.

**Comment by alexloehner** [comment]
can you please provide the content of ~/.linuxcounter/<hostname> and the output of lico-update.sh -s

Please remember to hide at least the machine_updatekey in your outputs!

**Comment by HaleyACS** [comment]
Sure, here you are.

smurphy@pandora:~/.linuxcounter$ cat pandora 
apikey="bf981f94d3a64227893f41d734dae625"
machine_id="287050"
machine_updatekey="xxxxxx"
hostname="pandora"
distribution="Ubuntu"
distversion="15.04 (Vivid Vervet)"
kernel="3.19.0-15-generic"
architecture="x86_64"
cpu="Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz"
cores="8"
flags="fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt"
memory="16337"
memoryFree="12394"
swap="15999"
swapFree="15999"
loadavg="0.20, 0.17, 0.15"
accounts="1"
diskspace="229919"
diskspaceFree="178489"
uptime="8180"
network="wireless"
online="1"
smurphy@pandora:~/.linuxcounter$ lico-update.sh -s
> Showing the current configuration and exiting...

### config start
apikey="bf981f94d3a64227893f41d734dae625"
machine_id="287050"
machine_updatekey="xxxxx"
hostname="pandora"
distribution="Ubuntu"
distversion="15.04 (Vivid Vervet)"
kernel="3.19.0-15-generic"
architecture="x86_64"
cpu="Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz"
cores="8"
flags="fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt"
memory="16337"
memoryFree="12394"
swap="15999"
swapFree="15999"
loadavg="0.20, 0.17, 0.15"
accounts="1"
diskspace="229919"
diskspaceFree="178489"
uptime="8180"
network="wireless"
online="1"
### config end

**Comment by alexloehner** [comment]
erm... closed by accident? Or is it working now?

**Comment by HaleyACS** [comment]
Closed by accident. Sorry ;)

**Comment by zenjive** [comment]
I think I'm having the same problem. I have 4 devices, 3 of which do not update, despite the script not showing any errors. The one system that is updating was added very recently, while the others are well over a year old.

**Comment by HaleyACS** [comment]
I can confirm that all my systems are registered for many years already ... So it seem to be due to the age ? or the old entry :}

**Comment by zenjive** [comment]
Ok, I think I fixed my issue. I was using what I thought was the latest, the 0.3.20 version from the launchpad ppa. I downloaded the github version, which reports as 0.0.4. This one created new machine entries with accurate system info. That was another thing with the 0.3.20 version, it wasn't getting accurate distribution info.
Anyway, everything seems to be working, I'll know for sure the next time the cron job runs.

**Comment by HaleyACS** [comment]
I am using 0.0.4 - and still have the issue.
Some parts are upgraded, others are not. Count of CPU Cores by example is Ok, CPU Type is not.

**Comment by zenjive** [comment]
Ok, so far all of my machines are updating. However, there's a weird problem I am having with an old Android tablet. It crashes whenever I try to run LiCo. It's 4.2.2 and my smartphone, which is running 5, works just fine. It's really not a big deal and would not surprise me if it was a problem with the tablet itself. But if you want me to make another post and log it as a separate issue, let me know.
